version: "3.8"
services:

    ##########################################
    #      GCC
    ##########################################

    # gcc 11
    build_gcc_11:
        image: justwhit3/qt-6.4.2:gcc_11
        volumes:
            - .:/proj
        working_dir: /proj
        command: >
            bash -c "cd /proj
            && cmake -B build
            && cmake --build build
            && rm -rf build

    ##########################################
    #      CLANG
    ##########################################

    # clang 6
    #build_clang_6:
    #    image: silkeh/clang:6
    #    network_mode: bridge
    #    volumes:
    #        - .:/proj
    #    container_name: build
    #    command: >
    #        bash -c "cd /proj
    #        && rm -rf build
    #        && cmake -B build -D CMAKE_CXX_compiler=clang++
    #        && cmake --build build"
