version: "3.8"
services:

    ##########################################
    #      GCC
    ##########################################

    # gcc 9
    build_gcc_9:
        image: justwhit3/qt-6.4.2:gcc_9
        volumes:
            - .:/proj
        working_dir: /proj
        command: >
            bash -c "cd /proj
            && chmod +x scripts/cmake_helper.sh && ./scripts/cmake_helper.sh
            && apt update -y && apt upgrade -y && apt install -y git
            && cmake -B build
            && cmake --build build
            && rm -rf build"

    # gcc 10
    build_gcc_10:
        image: justwhit3/qt-6.4.2:gcc_10
        volumes:
            - .:/proj
        working_dir: /proj
        command: >
            bash -c "cd /proj
            && chmod +x scripts/cmake_helper.sh && ./scripts/cmake_helper.sh
            && apt update -y && apt upgrade -y && apt install -y git
            && cmake -B build
            && cmake --build build
            && rm -rf build"

    # gcc 11
    build_gcc_11:
        image: justwhit3/qt-6.4.2:gcc_11
        volumes:
            - .:/proj
        working_dir: /proj
        command: >
            bash -c "cd /proj
            && chmod +x scripts/cmake_helper.sh && ./scripts/cmake_helper.sh
            && apt update -y && apt upgrade -y && apt install -y git
            && cmake -B build
            && cmake --build build
            && rm -rf build"

    # gcc 12
    build_gcc_12:
        image: justwhit3/qt-6.4.2:gcc_12
        volumes:
            - .:/proj
        working_dir: /proj
        command: >
            bash -c "cd /proj
            && chmod +x scripts/cmake_helper.sh && ./scripts/cmake_helper.sh
            && apt update -y && apt upgrade -y && apt install -y git
            && git config --global http.sslverify "false"
            && cmake -B build
            && cmake --build build
            && rm -rf build"

    ##########################################
    #      CLANG
    ##########################################

    # clang 6
    #build_clang_6:
    #    image: silkeh/clang:6
    #    network_mode: bridge
    #    volumes:
    #        - .:/proj
    #    container_name: build
    #    command: >
    #        bash -c "cd /proj
    #        && rm -rf build
    #        && cmake -B build -D CMAKE_CXX_compiler=clang++
    #        && cmake --build build"
