version: "2"
services:

    ##########################################
    #      GCC
    ##########################################

    # gcc 9
    build_gcc_9:
        image: vookimedlo/ubuntu-qt:qt6_latestDistroOfficial_gcc_lunar
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && apt install software-properties-common
            && apt update
            && apt install gcc-9
            && apt install g++-9
            && rm -rf build
            && CC=/usr/bin/gcc-9 CXX=/usr/bin/g++-9 cmake -B build
            && cmake --build build"

    # gcc 10
    build_gcc_10:
        image: vookimedlo/ubuntu-qt:qt6_latestDistroOfficial_gcc_lunar
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && apt install software-properties-common
            && apt update
            && apt install gcc-10
            && apt install g++-10
            && rm -rf build
            && CC=/usr/bin/gcc-10 CXX=/usr/bin/g++-10 cmake -B build
            && cmake --build build"

    # gcc 11
    build_gcc_11:
        image: vookimedlo/ubuntu-qt:qt6_latestDistroOfficial_gcc_lunar
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && apt install software-properties-common
            && apt update
            && apt install gcc-11
            && apt install g++-11
            && rm -rf build
            && CC=/usr/bin/gcc-11 CXX=/usr/bin/g++-11 cmake -B build
            && cmake --build build"

    # gcc 12
    build_gcc_12:
        image: vookimedlo/ubuntu-qt:qt6_latestDistroOfficial_gcc_lunar
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && apt install software-properties-common
            && apt update
            && apt install gcc-12
            && apt install g++-12
            && rm -rf build
            && CC=/usr/bin/gcc-12 CXX=/usr/bin/g++-12 cmake -B build
            && cmake --build build"

    ##########################################
    #      CLANG
    ##########################################

    # clang 15
    build_clang_15:
        image: vookimedlo/ubuntu-qt:qt6_latestDistroOfficial_gcc_lunar
        network_mode: bridge
        volumes:
            - .:/proj
        container_name: build
        command: >
            bash -c "cd /proj
            && add-apt-repository ppa:ubuntu-toolchain-r/test
            && apt update
            && apt install libclang-dev clang
            && rm -rf build
            && CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake -B build
            && cmake --build build"
