name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '45 22 * * 0'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        language: [ 'cpp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Installing extra dependencies and compiling (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace justwhit3/qt-6.4.2:gcc_11 /bin/bash -c "
        chmod +x scripts/cmake_helper.sh && ./scripts/cmake_helper.sh
        apt update -y && apt upgrade -y && apt install -y git
        cmake -B build
        cmake --build build
        cmake --build build --target install"

    - name: Installing extra dependencies and compiling (MacOS)
      if: matrix.os == 'macos-latest'
      run: |
       cmake -B build
       cmake --build build
       sudo cmake --build build --target install